[global]
   workgroup = WORKGROUP
   security = user
   map to guest = Bad User
   interfaces = eth0 lo
   bind interfaces only = no

[Data]
   path = /run/import
   browseable = yes
   read only = no
   guest ok = yes
   force user = root

[TestFiles]
    path = /storage/test_files
    comment = Zusätzliche Testdaten für Agenten
    browseable = yes
    read only = no
    guest ok = yes
    force user = root